server:
  port: 8761

spring:
  application:
    name: ead-service-registry

eureka:
  client:
    registerWithEureka: false # Ele nao deve ser cliente apenas o servidor
    fetchRegistry: false # Ele nao busca um registro no Eureka
