server:
  port: 8761

spring:
  application:
    name: ead-service-registry

ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  client:
    registerWithEureka: false # Ele nao deve ser cliente apenas o servidor
    fetchRegistry: false # Ele nao busca um registro no Eureka
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
